// <auto-generated />
using System;
using GymQuest.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymQuest.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GymQuestDbContext))]
    partial class GymQuestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymQuest.Domain.Entities.Ejercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("FactorXp")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Ejercicios", (string)null);
                });

            modelBuilder.Entity("GymQuest.Domain.Entities.Heroe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Consistencia")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienciaActual")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienciaParaSiguienteNivel")
                        .HasColumnType("integer");

                    b.Property<int>("Fuerza")
                        .HasColumnType("integer");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<int>("Resistencia")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Heroes", (string)null);
                });

            modelBuilder.Entity("GymQuest.Domain.Entities.Logro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Desbloqueado")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("FechaDesbloqueo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HeroeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("HeroeId");

                    b.ToTable("Logros", (string)null);
                });

            modelBuilder.Entity("GymQuest.Domain.Entities.Mision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Completada")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HeroeId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProgresoActual")
                        .HasColumnType("integer");

                    b.Property<string>("TipoObjetivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ValorObjetivo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeroeId");

                    b.ToTable("Misiones", (string)null);
                });

            modelBuilder.Entity("GymQuest.Domain.Entities.Racha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DiasConsecutivos")
                        .HasColumnType("integer");

                    b.Property<int>("DiasProgramadosPorSemana")
                        .HasColumnType("integer");

                    b.Property<Guid>("HeroeId")
                        .HasColumnType("uuid");

                    b.Property<int>("PocionesDeDescansoDisponibles")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimaFechaEntrenada")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HeroeId")
                        .IsUnique();

                    b.ToTable("Rachas", (string)null);
                });

            modelBuilder.Entity("GymQuest.Domain.Entities.Rutina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EsPlantillaPredeterminada")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Rutinas", (string)null);
                });

            modelBuilder.Entity("GymQuest.Domain.Entities.RutinaEjercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EjercicioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PesoInicial")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("RepeticionesObjetivo")
                        .HasColumnType("integer");

                    b.Property<Guid>("RutinaId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeriesObjetivo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("RutinaId");

                    b.ToTable("RutinaEjercicios", (string)null);
                });

            modelBuilder.Entity("GymQuest.Domain.Entities.SerieRealizada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EjercicioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsRecordPersonal")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PesoLevantado")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("RepeticionesRealizadas")
                        .HasColumnType("integer");

                    b.Property<Guid>("SesionEntrenamientoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("SesionEntrenamientoId");

                    b.ToTable("SeriesRealizadas", (string)null);
                });

            modelBuilder.Entity("GymQuest.Domain.Entities.SesionEntrenamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Completada")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HeroeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RutinaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HeroeId");

                    b.ToTable("SesionesEntrenamiento", (string)null);
                });

            modelBuilder.Entity("GymQuest.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("GymQuest.Domain.Entities.RutinaEjercicio", b =>
                {
                    b.HasOne("GymQuest.Domain.Entities.Rutina", null)
                        .WithMany("Ejercicios")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymQuest.Domain.Entities.SerieRealizada", b =>
                {
                    b.HasOne("GymQuest.Domain.Entities.SesionEntrenamiento", null)
                        .WithMany("Series")
                        .HasForeignKey("SesionEntrenamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymQuest.Domain.Entities.Rutina", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("GymQuest.Domain.Entities.SesionEntrenamiento", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
